# Generated by Django 5.0.12 on 2025-02-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('views_2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Escola',
        ),
    ]
